plugins:
  - babel
  - jest
env:
  browser: true
  es2021: true
  node: true
  jest: true
parser: babel-eslint
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  { import/no-extraneous-dependencies: ['error', { 'devDependencies': true }] }
