root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - 'jest'
env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-typescript/base
  - plugin:jest/recommended
  - plugin:@typescript-eslint/recommended
parserOptions: { project: './tsconfig.json' }
settings: { import/resolver: { node: { extensions: ['.js', '.ts'] } } }
rules:
  { import/no-extraneous-dependencies: ['error', { 'devDependencies': true }] }
overrides:
  [
    {
      files: ['.ts'],
      rules: { '@typescript-eslint/explicit-function-return-type': ['error'] },
    },
  ]
